### ISSUE TITLE
cylc7: conda environment

### ISSUE THREAD

**Issue by oliver-sanders** [cylc/cylc-flow#3958]
Follow on to #3954 

Release Cylc 7.8.7 on Conda Forge.

Fossilise Cylc7 by uploading it to Conda Forge.

This would allow the installation of Cylc7 and Cylc8 side-by-side under the same infrastructure and may make it easier to install Python2 where required.

The only barrier I can see is PyGTK, however, there is a user channel we can use, otherwise we could go via pip:

```yml
name: cylc7 
channels: 
  - conda-forge 
  - ska  # for pygtk https://anaconda.org/ska/pygtk 
  - defaults 
dependencies: 
  - python >=2.7,<3.0 
  - openssl 
  - pyopenssl 
  - requests >=2.4.2 
  - gtk2 
  - graphviz 
  - pygraphviz 
  - empy 
  - pygtk  # linux 64bit only
```

**Comment by hjoliver** [comment]
I tried conda channel ska/pygtk via conda some time ago. It installs, but it seemed to be quite severely broken. It is 6+ years old so maybe its not compatible with the latest (and only?) Python 2 available now on conda?  Might be a blocker unless we go to the effort to make our own pygtk conda package :vomiting_face:

**Comment by oliver-sanders** [comment]
Dammit.

**Comment by oliver-sanders** [comment]
Got it working with, [ruamel-venvgtk](https://sourceforge.net/projects/ruamel-venvgtk/), old code but it's for an old library on old Python so that's no surprise:

```yml
name: cylc7 
channels: 
  - conda-forge 
  - defaults 
dependencies: 
  - python >=2.7,<3.0 
  - openssl 
  - pyopenssl 
  - requests >=2.4.2 
  - gtk2 
  - graphviz 
  - pygraphviz 
  - empy 
  - pip:
    - ruamel.venvgtk
```
