### ISSUE TITLE
cylc lint - site/workflow specific rules?

### ISSUE THREAD

**Issue by ColemanTom** [cylc/cylc-flow#5866]
### Problem

A site or workflow itself may have specific lint requirements that are very specific and not really suitable for the standard set of rules. Is there a way to add your own as plugins (e.g. via entry_points or similar)?

### Proposed Solution

Allow site specific rules be added and used via entry_points or similar.

**Comment by wxtim** [comment]
Would it be sane (and easier to implement?) to allow regex based rules to be defined in the pyproject TOML file?

@ColemanTom - What sort of rules do you want to implement?

My thought would be:

```toml
[cylc-lint]
rulesets.P.name = "My Custom Rulez" 
rulesets.P.letter = "P"      # The letter for your rule-set
rulesets.P.1.rule = "(.*)"   # A regex
rulesets.P.1.description = "What the problem is"
```

Equally, I don't see why we can't allow entry points - but why make it more complex than necessary?
